package es.csic.getsensordata.data_sensors.definition

import android.hardware.SensorEvent
import android.os.Bundle
import android.util.Log

/**
 * Event generated by a `DataSensor` instance.
 */
class DataSensorEvent(
    val dataSensor: DataSensor,
    sensorEvent: SensorEvent?,
    val data: Bundle?,
    val tag: String?
) {
    val values: FloatArray
    val accuracy: Int
    val timestamp: Long // nanoseconds

    init {
        Log.v(
            Tag, "constructor(" +
                    "dataSensor=$dataSensor, " +
                    "sensorEvent=$sensorEvent, " +
                    "data=$data, " +
                    "tag=$tag)"
        )
        values = sensorEvent?.values ?: FloatArray(0)
        accuracy = sensorEvent?.accuracy ?: 0
        timestamp = sensorEvent?.timestamp ?: System.nanoTime()
    }

    companion object {
        private val Tag = DataSensorEvent::class.java.simpleName
    }
}
